apiVersion: apps/v1
kind: Deployment
metadata:
  name: stubbornjava-deployment
  labels:
    app: sj-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sj-web
  template:
    metadata:
      labels:
        app: sj-web
    spec:
      containers:
        - name: sj-web
          image: docker.pkg.github.com/stubbornjava/stubbornjava/stubbornjava-webapp:qa
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "prod"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/
      volumes:
        - name: config-volume
          configMap:
            name: sj-web-config-prod
            items:
            - key: sjweb.production.conf
              path: sjweb.production.conf
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: sj-web-lb
spec:
  selector:
    app: sj-web
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sj-web-config-prod
data:
  # Or set as complete file contents (even JSON!)
  sjweb.production.conf: | 
    cdn {
      host="https://cdn.stubbornjava.com"
    }
