apiVersion: apps/v1
kind: Deployment
metadata:
  name: stubbornjava-deployment
  labels:
    app: sj-web
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: stubbornjava
    meta.helm.sh/release-namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable
                         # during the rolling update
  selector:
    matchLabels:
      app: sj-web
  template:
    metadata:
      labels:
        app: sj-web
    spec:
      containers:
        - name: sj-web
          image: {{ required "image input required" .Values.image | quote }}
          resources:
            limits:
              cpu: "0.5"
              memory: "250M"
            requests:
              cpu: "0.25"
              memory: "150M"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3
          # Right now this is all we need. Make this more sophisticated once we add a database.
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "prod"
            - name: LOG_APPENDER
              value: "JSON"
            - name: github.clientId
              valueFrom:
                secretKeyRef:
                  name: githubcreds
                  key: github.client_id
            - name: github.clientSecret
              valueFrom:
                secretKeyRef:
                  name: githubcreds
                  key: github.client_secret
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/
      volumes:
        - name: config-volume
          configMap:
            name: sj-web-config-prod
            items:
            - key: sjweb.production.conf
              path: sjweb.production.conf
      imagePullSecrets:
        - name: ghregistry

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: sj-web-lb
# spec:
#   selector:
#     app: stubbornjava-deployment
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#   # externalTrafficPolicy: Local
#   type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: sj-web-nodeport
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: stubbornjava
    meta.helm.sh/release-namespace: default
spec:
  type: NodePort
  selector:
    app: sj-web
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30030

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sj-web-config-prod
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: stubbornjava
    meta.helm.sh/release-namespace: default
data:
  # Or set as complete file contents (even JSON!)
  sjweb.production.conf: | 
    # cdn {
    #   # host="https://cdn.stubbornjava.com"
    # }
